//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarfetchClass.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabControlToggle
    {
        public int idApplication { get; set; }
        public int idVersion { get; set; }
        public string strKey { get; set; }
        public bool strValue { get; set; }
    }
}
